title: "Theo Emmerich"
baseURL: "http://theoemmerich.com/"
defaultContentLanguage: en
languageCode: en-US

theme: ["github.com/wowchemy/starter-hugo-academic"]

# Menu configuration
menu:
  main:
    - name: Publications
      url: publication/
      weight: 1
    - name: CV
      url: cv/
      weight: 2

# General site configuration
params:
  main_menu:
    enable: true
  layout:
    navbar_fixed: true

# Directory Hugo will publish the site to
publishDir: "public"
