title: "Theo Emmerich"
baseURL: "http://theoemmerich.com/"
defaultContentLanguage: en
languageCode: en-US

theme: ["github.com/wowchemy/starter-hugo-academic"]

menu:
  main:
    - name: Publications
      url: publication/
      weight: 1
    - name: CV
      url: cv/
      weight: 2

params:
  main_menu:
    enable: true
  layout:
    navbar_fixed: true

  # Profile settings
  profile:
    enable: true
    name: "Theo Emmerich"
    image: "avatar.jpg"  # Place ton image dans static/media/avatar.jpg
    links:
      - icon: linkedin
        icon_pack: fab
        name: LinkedIn
        url: "https://www.linkedin.com/in/ton-lien"
      - icon: google-scholar
        icon_pack: ai
        name: Google Scholar
        url: "https://scholar.google.com/citations?user=tonID"

publishDir: "public"
